# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Design Web Development -  Baguio City | Thirdkraft
email: thirdkraft@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thirdkraft Web Development Team is a group of web craftsmen, who are expert in professional web design and web development – with experience in the craft of web creating for a decade. Thirdkraft is composed of team members who are currently based in Baguio City and Metro Manila Philippines.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.thirdkraft.com" # the base hostname & protocol for your site
twitter_username: marcelbadua
github_username:  marcelbadua

# Build settings
markdown: kramdown
include: ['_pages']
